### ISSUE TITLE
Dropping a Mesh future causes panics in h2

### ISSUE THREAD

**Issue by nytopop** [nytopop/blip#7]
Pops up a lot in tests. Leaving this issue here so I don't forget about it.

This is probably the same as hyperium/h2/issues/417. From my (very) limited exploration into the cause, it *seems* like [`drop_stream_ref`](https://github.com/hyperium/h2/blob/f7718b5b19d031ecaa85fb1bfd7bfc9e158b69a5/src/proto/streams/streams.rs#L1277) doesn't actually remove the slab entry, although there's enough indirection present that I'm fairly unsure of that being the case.

```
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.slab.is_empty()', /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.2.2/src/proto/streams/store.rs:212:13
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.slab.is_empty()', /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.2.2/src/proto/streams/store.rs:212:13
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.slab.is_empty()', /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.2.2/src/proto/streams/store.rs:212:13
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.slab.is_empty()', /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.2.2/src/proto/streams/store.rs:212:13
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.slab.is_empty()', /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.2.2/src/proto/streams/store.rs:212:13
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.slab.is_empty()', /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.2.2/src/proto/streams/store.rs:212:13
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.slab.is_empty()', /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.2.2/src/proto/streams/store.rs:212:13
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.slab.is_empty()', /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.2.2/src/proto/streams/store.rs:212:13
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.slab.is_empty()', /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.2.2/src/proto/streams/store.rs:212:13
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.slab.is_empty()', /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.2.2/src/proto/streams/store.rs:212:13
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.slab.is_empty()', /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.2.2/src/proto/streams/store.rs:212:13
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.slab.is_empty()', /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.2.2/src/proto/streams/store.rs:212:13
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.slab.is_empty()', /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.2.2/src/proto/streams/store.rs:212:13
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.slab.is_empty()', /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.2.2/src/proto/streams/store.rs:212:13
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.slab.is_empty()', /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.2.2/src/proto/streams/store.rs:212:13
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.slab.is_empty()', /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.2.2/src/proto/streams/store.rs:212:13
```

**Comment by nytopop** [comment]
No longer an issue with h2 v0.2.5.
